name: Build and upload tinos2 ISO




on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up permissions
      run: sudo chmod +x ./ubuntu-install-deps.sh
    - name: install dependencies
      run: ./ubuntu-install-deps.sh
    - name: make
      run: make IMAGE_NAME=tinos2ce
    - uses: actions/upload-artifact@v7
      with:
        name: tinos2ce
        path: |
          bin/*.iso
          !bin/*.elf
          !bin/kernel/
        retention-days: 10
